const RAW_COUNTRY_CODES='ad ae af ag ai al am ao aq ar as at au aw ax az ba bb bd be bf bg bh bi bj bl bm bn bo bq br bs bt bv bw by bz ca cc cd cf cg ch ci ck cl cm cn co cr cu cv cw cx cy cz de dj dk dm do dz ec ee eg eh er es et fi fj fk fm fo fr ga gb gd ge gf gg gh gi gl gm gn gp gq gr gs gt gu gw gy hk hm hn hr ht hu id ie il im in io iq ir is it je jm jo jp ke kg kh ki km kn kp kr kw ky kz la lb lc li lk lr ls lt lu lv ly ma mc md me mf mg mh mk ml mm mn mo mp mq mr ms mt mu mv mw mx my mz na nc ne nf ng ni nl no np nr nu nz om pa pe pf pg ph pk pl pm pn pr ps pt pw py qa re ro rs ru rw sa sb sc sd se sg sh si sj sk sl sm sn so sr ss st sv sx sy sz tc td tf tg th tj tk tl tm tn to tr tt tv tw tz ua ug um us uy uz va vc ve vg vi vn vu wf ws ye yt za zm zw'.split(' ');
const names=new Intl.DisplayNames(['en'],{type:'region'});
const label=code=>{try{return names.of(code.toUpperCase())||code.toUpperCase()}catch{return code.toUpperCase()}};
const COUNTRY_CODES=[...RAW_COUNTRY_CODES].sort((a,b)=>label(a).localeCompare(label(b),'en'));
const flag=code=>code.toUpperCase().replace(/[A-Z]/g,c=>String.fromCodePoint(127397+c.charCodeAt()));
function populate(select,withAll=false){if(!select||select.dataset.countriesExpanded==='1')return;const current=select.value;select.innerHTML=(withAll?'<option value="all">すべての国</option>':'')+COUNTRY_CODES.map(c=>`<option value="${c}">${label(c)}</option>`).join('');if([...select.options].some(o=>o.value===current))select.value=current;select.dataset.countriesExpanded='1';}
function improveProfileCountry(){const el=document.querySelector('.profile-copy > span');if(!el)return;const text=el.textContent.trim(),match=text.match(/(?:🌐\s*)?([a-z]{2})$/i);if(!match)return;const code=match[1].toLowerCase();if(!COUNTRY_CODES.includes(code))return;const expected=`${flag(code)} ${label(code)}`;if(text!==expected)el.textContent=expected;}
function improveInsights(){const box=document.querySelector('#insightStats');if(!box)return;box.setAttribute('aria-label','今月のインサイト');for(const stat of box.querySelectorAll('.insight-stat')){const b=stat.querySelector('b'),s=stat.querySelector('span');if(b&&s){b.classList.add('insight-value');s.classList.add('insight-label');}}}
function improveHealthCopy(){
 const row=document.querySelector('[data-sheet="watch-setup"]');const button=row?.querySelector('button');if(button)button.textContent='Apple Watch / Health連携（Duffy・Nike）';
 const title=document.querySelector('#sheetTitle');if(!title)return;
 if(title.textContent.includes('Apple Watch連携')){
  title.textContent='Apple Watch / Health連携';const desc=document.querySelector('#sheetContent .sheet-description');
  if(desc&&!desc.dataset.healthCopy){desc.textContent='DuffyやNike Run ClubがAppleヘルスケアへ保存した歩数・歩行＋走行距離を、iPhoneコンパニオンアプリ経由でJasmy Runへ同期します。Jasmy Runへの位置情報許可は不要です。同期データは未認定として表示し、ランキング・チーム認定距離・チャレンジには加算しません。';desc.dataset.healthCopy='1';}
  const muted=document.querySelector('#sheetContent .small.muted');if(muted&&!muted.dataset.healthCopy){muted.textContent='iOSコンパニオン「Jasmy Health Sync」は現在ベータ実装です。ソースコードは用意されていますが、App Store / TestFlightでの一般配布はまだ開始していません。配布後はこの画面で連携コードを発行して接続します。';muted.dataset.healthCopy='1';}
 }
 if(title.textContent.includes('連携コードを発行しました')){const desc=document.querySelector('#sheetContent .sheet-description');if(desc&&!desc.dataset.healthTokenCopy){desc.textContent='このコードは今だけ表示されます。iOSコンパニオンアプリ「Jasmy Health Sync」の連携コード欄に貼り付けてください。再表示はできません。';desc.dataset.healthTokenCopy='1';}}
}
function setupRunSourceChooser(){
 const start=document.querySelector('#homeStartButton');if(!start||start.dataset.sourceChooserReady==='1')return;
 start.dataset.sourceChooserReady='1';const originalStart=start.onclick;const chooser=document.createElement('section');chooser.className='run-source-selector';chooser.setAttribute('aria-label','記録方法を選択');
 chooser.innerHTML=`<div class="run-source-title"><b>記録方法</b><span>位置情報を使わない記録も選べます</span></div><div class="run-source-options"><button type="button" class="run-source-option" data-run-source="gps" aria-pressed="false"><span class="run-source-icon"><svg class="icon"><use href="#i-target"></use></svg></span><span><b>GPSで記録</b><small>リアルタイム計測</small></span></button><button type="button" class="run-source-option" data-run-source="watch" aria-pressed="false"><span class="run-source-icon"><svg class="icon"><use href="#i-link"></use></svg></span><span><b>Apple Watchから記録</b><small>Healthから同期</small></span></button></div><p class="run-source-help" id="runSourceHelp"></p>`;
 start.before(chooser);const options=[...chooser.querySelectorAll('[data-run-source]')],help=chooser.querySelector('#runSourceHelp');let source='gps';try{source=localStorage.getItem('jasmy-run-source')==='watch'?'watch':'gps';}catch{}
 const activate=next=>{source=next==='watch'?'watch':'gps';for(const option of options){const active=option.dataset.runSource===source;option.classList.toggle('active',active);option.setAttribute('aria-pressed',String(active));}if(source==='watch'){start.innerHTML='<svg class="icon"><use href="#i-link"></use></svg>APPLE WATCHから記録';help.textContent='Appleヘルスケアの歩数・歩行＋走行距離を同期します。Jasmy Runへの位置情報許可は不要です。現在は未認定データとして扱います。';}else{start.innerHTML='<svg class="icon"><use href="#i-run"></use></svg>GPSで記録を開始';help.textContent='現在地をリアルタイム計測します。保存後に認定されるとランキング・チーム・チャレンジの対象になります。';}try{localStorage.setItem('jasmy-run-source',source);}catch{}};
 for(const option of options)option.addEventListener('click',()=>activate(option.dataset.runSource));activate(source);
 start.onclick=event=>{if(source==='watch'){event.preventDefault();const watchSetup=document.querySelector('[data-sheet="watch-setup"]');if(watchSetup){watchSetup.click();return;}const fallback=document.querySelector('#homeWatchLine');if(fallback)fallback.hidden=false;return;}if(typeof originalStart==='function')return originalStart.call(start,event);document.querySelector('[data-nav-go="run"]')?.click();};
}
function apply(){populate(document.querySelector('#countrySelect'),true);populate(document.querySelector('#country'));improveProfileCountry();improveInsights();improveHealthCopy();setupRunSourceChooser();}
const style=document.createElement('style');style.textContent=`
#insightStats.insight-stats{display:grid!important;grid-template-columns:repeat(3,minmax(0,1fr))!important;gap:8px!important;width:100%!important}
#insightStats .insight-stat{min-width:0!important;padding:12px 8px!important;border:1px solid #eee7df!important;border-radius:12px!important;background:#fffaf5!important;text-align:center!important;display:flex!important;flex-direction:column!important;gap:5px!important;justify-content:center!important}
#insightStats .insight-value{font-size:17px!important;line-height:1.15!important;white-space:nowrap!important}
#insightStats .insight-label{font-size:10px!important;line-height:1.35!important;color:#6b7280!important;white-space:normal!important;word-break:keep-all!important}
.run-source-selector{margin:16px 0 10px;padding:14px;border:1px solid #eee7df;border-radius:18px;background:#fff;box-shadow:0 5px 18px rgba(72,52,35,.05)}
.run-source-title{display:flex;align-items:baseline;justify-content:space-between;gap:10px;margin-bottom:10px}.run-source-title b{font-size:14px}.run-source-title span{font-size:10px;color:#7c746c;text-align:right}
.run-source-options{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.run-source-option{appearance:none;border:1.5px solid #e6dfd7;border-radius:14px;background:#fff;padding:11px 9px;display:flex;align-items:center;gap:8px;text-align:left;color:inherit;min-width:0;cursor:pointer}.run-source-option.active{border-color:#f49a42;background:#fff8f0;box-shadow:0 0 0 1px rgba(244,154,66,.12)}.run-source-option:focus-visible{outline:3px solid rgba(244,154,66,.28);outline-offset:2px}.run-source-icon{width:32px;height:32px;border-radius:10px;background:#f6f3ef;display:grid;place-items:center;flex:0 0 auto}.run-source-option.active .run-source-icon{background:#fff0df;color:#d97719}.run-source-option b{display:block;font-size:12px;line-height:1.25}.run-source-option small{display:block;margin-top:3px;font-size:9px;color:#7c746c;line-height:1.2}.run-source-help{margin:10px 2px 0;font-size:10px;line-height:1.55;color:#6b7280}.home-start[data-run-source="watch"]{background:#333}
@media(max-width:390px){#insightStats.insight-stats{grid-template-columns:1fr!important}#insightStats .insight-stat{display:grid!important;grid-template-columns:1fr 1.3fr!important;text-align:left!important;align-items:center!important}#insightStats .insight-label{text-align:right!important;font-size:11px!important}.run-source-title{align-items:flex-start;flex-direction:column;gap:2px}.run-source-title span{text-align:left}.run-source-options{grid-template-columns:1fr}.run-source-option{padding:10px 12px}.run-source-option b{font-size:13px}}
`;document.head.append(style);
const observer=new MutationObserver(()=>apply());observer.observe(document.body,{childList:true,subtree:true});apply();
