const COUNTRY_CODES=['jp','us','gb','ca','au','nz','sg','kr','cn','tw','hk','in','id','th','vn','my','ph','ae','sa','il','tr','de','fr','it','es','pt','nl','be','ch','at','se','no','dk','fi','ie','pl','cz','gr','ro','hu','ua','br','mx','ar','cl','co','pe','za','eg','ng','ke'];
const names=new Intl.DisplayNames(['en'],{type:'region'});
const label=code=>{try{return names.of(code.toUpperCase())||code.toUpperCase()}catch{return code.toUpperCase()}};
function populate(select,withAll=false){if(!select)return;const current=select.value;select.innerHTML=(withAll?'<option value="all">すべての国</option>':'')+COUNTRY_CODES.map(c=>`<option value="${c}">${label(c)}</option>`).join('');if([...select.options].some(o=>o.value===current))select.value=current;}
function improveInsights(){const box=document.querySelector('#insightStats');if(!box)return;box.setAttribute('aria-label','今月のインサイト');for(const stat of box.querySelectorAll('.insight-stat')){const b=stat.querySelector('b'),s=stat.querySelector('span');if(b&&s){b.classList.add('insight-value');s.classList.add('insight-label');}}
}
function improveHealthCopy(){const row=[...document.querySelectorAll('.setting-row')].find(r=>r.textContent.includes('Apple Watch連携（Duffy）'));const button=row?.querySelector('button');if(button)button.textContent='Apple Watch / Health連携（Duffy・Nike）';const title=document.querySelector('#sheetTitle');if(title?.textContent.includes('Apple Watch連携')){title.textContent='Apple Watch / Health連携';const desc=document.querySelector('#sheetContent .sheet-description');if(desc)desc.textContent='DuffyやNike Run ClubがAppleヘルスケアへ保存した歩数・歩行＋走行距離を、Jasmy Health Sync経由で読み取ります。位置情報をJasmy Runへ許可しなくても、日々の活動量をホームに表示できます。ランキング・認定距離・チャレンジには加算しません。';const muted=document.querySelector('#sheetContent .small.muted');if(muted)muted.textContent='iPhoneの「設定 → プライバシーとセキュリティ → ヘルスケア」でDuffy / Nike Run Clubの共有を許可し、Jasmy Health Syncにも歩数と歩行＋走行距離の読み取りを許可してください。';}}
function apply(){populate(document.querySelector('#countrySelect'),true);populate(document.querySelector('#country'));improveInsights();improveHealthCopy();}
const style=document.createElement('style');style.textContent=`
#insightStats.insight-stats{display:grid!important;grid-template-columns:repeat(3,minmax(0,1fr))!important;gap:8px!important;width:100%!important}
#insightStats .insight-stat{min-width:0!important;padding:12px 8px!important;border:1px solid #eee7df!important;border-radius:12px!important;background:#fffaf5!important;text-align:center!important;display:flex!important;flex-direction:column!important;gap:5px!important;justify-content:center!important}
#insightStats .insight-value{font-size:17px!important;line-height:1.15!important;white-space:nowrap!important}
#insightStats .insight-label{font-size:10px!important;line-height:1.35!important;color:#6b7280!important;white-space:normal!important;word-break:keep-all!important}
@media(max-width:390px){#insightStats.insight-stats{grid-template-columns:1fr!important}#insightStats .insight-stat{display:grid!important;grid-template-columns:1fr 1.3fr!important;text-align:left!important;align-items:center!important}#insightStats .insight-label{text-align:right!important;font-size:11px!important}}
`;document.head.append(style);
const observer=new MutationObserver(()=>apply());observer.observe(document.body,{childList:true,subtree:true});apply();
