const RAW_COUNTRY_CODES='ad ae af ag ai al am ao aq ar as at au aw ax az ba bb bd be bf bg bh bi bj bl bm bn bo bq br bs bt bv bw by bz ca cc cd cf cg ch ci ck cl cm cn co cr cu cv cw cx cy cz de dj dk dm do dz ec ee eg eh er es et fi fj fk fm fo fr ga gb gd ge gf gg gh gi gl gm gn gp gq gr gs gt gu gw gy hk hm hn hr ht hu id ie il im in io iq ir is it je jm jo jp ke kg kh ki km kn kp kr kw ky kz la lb lc li lk lr ls lt lu lv ly ma mc md me mf mg mh mk ml mm mn mo mp mq mr ms mt mu mv mw mx my mz na nc ne nf ng ni nl no np nr nu nz om pa pe pf pg ph pk pl pm pn pr ps pt pw py qa re ro rs ru rw sa sb sc sd se sg sh si sj sk sl sm sn so sr ss st sv sx sy sz tc td tf tg th tj tk tl tm tn to tr tt tv tw tz ua ug um us uy uz va vc ve vg vi vn vu wf ws ye yt za zm zw'.split(' ');
const names=new Intl.DisplayNames(['en'],{type:'region'});
const label=code=>{try{return names.of(code.toUpperCase())||code.toUpperCase()}catch{return code.toUpperCase()}};
const COUNTRY_CODES=[...RAW_COUNTRY_CODES].sort((a,b)=>label(a).localeCompare(label(b),'en'));
const flag=code=>code.toUpperCase().replace(/[A-Z]/g,c=>String.fromCodePoint(127397+c.charCodeAt()));
function populate(select,withAll=false){if(!select||select.dataset.countriesExpanded==='1')return;const current=select.value;select.innerHTML=(withAll?'<option value="all">すべての国</option>':'')+COUNTRY_CODES.map(c=>`<option value="${c}">${label(c)}</option>`).join('');if([...select.options].some(o=>o.value===current))select.value=current;select.dataset.countriesExpanded='1';}
function improveProfileCountry(){const el=document.querySelector('.profile-copy > span');if(!el)return;const text=el.textContent.trim(),match=text.match(/(?:🌐\s*)?([a-z]{2})$/i);if(!match)return;const code=match[1].toLowerCase();if(!COUNTRY_CODES.includes(code))return;const expected=`${flag(code)} ${label(code)}`;if(text!==expected)el.textContent=expected;}
function improveInsights(){const box=document.querySelector('#insightStats');if(!box)return;box.setAttribute('aria-label','今月のインサイト');for(const stat of box.querySelectorAll('.insight-stat')){const b=stat.querySelector('b'),s=stat.querySelector('span');if(b&&s){b.classList.add('insight-value');s.classList.add('insight-label');}}}
function improveHealthCopy(){const row=[...document.querySelectorAll('.setting-row')].find(r=>r.textContent.includes('Apple Watch連携（Duffy）'));const button=row?.querySelector('button');if(button)button.textContent='Apple Watch / Health連携（Duffy・Nike）';const title=document.querySelector('#sheetTitle');if(title?.textContent.includes('Apple Watch連携')){title.textContent='Apple Watch / Health連携';const desc=document.querySelector('#sheetContent .sheet-description');if(desc&&!desc.dataset.healthCopy){desc.textContent='DuffyやNike Run ClubがAppleヘルスケアへ保存した歩数・歩行＋走行距離を、Jasmy Health Sync経由で読み取ります。位置情報をJasmy Runへ許可しなくても、日々の活動量をホームに表示できます。ランキング・認定距離・チャレンジには加算しません。';desc.dataset.healthCopy='1';}const muted=document.querySelector('#sheetContent .small.muted');if(muted&&!muted.dataset.healthCopy){muted.textContent='iPhoneの「設定 → プライバシーとセキュリティ → ヘルスケア」でDuffy / Nike Run Clubの共有を許可し、Jasmy Health Syncにも歩数と歩行＋走行距離の読み取りを許可してください。';muted.dataset.healthCopy='1';}}}
function apply(){populate(document.querySelector('#countrySelect'),true);populate(document.querySelector('#country'));improveProfileCountry();improveInsights();improveHealthCopy();}
const style=document.createElement('style');style.textContent=`
#insightStats.insight-stats{display:grid!important;grid-template-columns:repeat(3,minmax(0,1fr))!important;gap:8px!important;width:100%!important}
#insightStats .insight-stat{min-width:0!important;padding:12px 8px!important;border:1px solid #eee7df!important;border-radius:12px!important;background:#fffaf5!important;text-align:center!important;display:flex!important;flex-direction:column!important;gap:5px!important;justify-content:center!important}
#insightStats .insight-value{font-size:17px!important;line-height:1.15!important;white-space:nowrap!important}
#insightStats .insight-label{font-size:10px!important;line-height:1.35!important;color:#6b7280!important;white-space:normal!important;word-break:keep-all!important}
@media(max-width:390px){#insightStats.insight-stats{grid-template-columns:1fr!important}#insightStats .insight-stat{display:grid!important;grid-template-columns:1fr 1.3fr!important;text-align:left!important;align-items:center!important}#insightStats .insight-label{text-align:right!important;font-size:11px!important}}
`;document.head.append(style);
const observer=new MutationObserver(()=>apply());observer.observe(document.body,{childList:true,subtree:true});apply();
