// Translate text nodes without replacing elements or their event handlers.
// Keep source text per node so switching back also restores dynamic content.
const en={
'GPS利用不可':'GPS unavailable',
'この環境では位置情報を利用できません。時間の計測は続けられます。距離を計測するにはHTTPSのアプリURLをSafariまたはChromeで開いてください。':'Location is unavailable in this environment. You can still track time. To measure distance, open the HTTPS app URL in Safari or Chrome.',
'走るほど、':'Every run,','自分らしい未来へ。':'a future of your own.','自分のペースで、日々の走りを記録。':'Track your runs at your own pace.','PDL連携は準備中です。':'PDL integration is coming soon.','まずは端末保存でお使いいただけます。':'Start by saving runs on this device.',
'Jasmy PDLでログイン（準備中）':'Sign in with Jasmy PDL (coming soon)','メールでログイン・登録':'Sign in / Sign up with email','この端末だけに保存して使う':'Use device storage','PDLとは？':'What is PDL?','利用規約':'Terms of use','プライバシーポリシー':'Privacy policy','今日も、自分のペースで':'At your own pace, every day','今日の走行':"Today’s run",'今月の記録':'This month','世界ランキング':'Global rankings','ランキングを見る':'View rankings','チーム':'Team','チームを見る':'View team','走って北海道グルメを当てよう！':'Run for a chance to win Hokkaido food!','詳しく見る':'View details','走行履歴を見る':'Run history','時間':'Time','一時停止':'Pause','終了':'Finish','再開':'Resume','開始':'Start','よく頑張りました！':'Great run!','カロリー':'Calories','スプリット':'Splits','ペース':'Pace','標高 (m)':'Elevation (m)','ホームへ':'Go home','もう一度走る':'Run again','ランキング':'Rankings','個人':'Individual','今週':'This week','今月':'This month','全期間':'All time','国別':'By country','すべての国':'All countries','名前':'Name','距離 (km)':'Distance (km)','ランキングは認定済みの距離のみが対象です。':'Rankings include verified distances only.','概要':'Overview','メンバー':'Members','チャレンジ':'Challenge','開催中':'Current','過去のチャレンジ':'Past challenges','開催期間':'Dates','賞品':'Prize','北海道海鮮セット（30名様）':'Hokkaido seafood set (30 winners)','北海道海鮮セット':'Hokkaido seafood set','北海道グルメ':'Hokkaido food','スポンサー未決定':'Sponsor to be announced','企画イメージ・実際の開催と抽選は未開始':'Concept preview · campaign and draw not yet open','参加状況':'Your entries','今月の走行日数：':'Running days this month:','日':'days','次のエントリー':'Next entry','抽選予定日':'Draw date','プロフィールを編集':'Edit profile','データ':'Data','同意管理':'Consent','設定':'Settings','ランニングデータ':'Running data','走行回数':'Total runs','ランニング日数':'Running days','今月のインサイト':'Monthly insights','平均ペース':'Average pace','あなたのデータは、あなたが管理する。':'Your data. Your control.','保存されているデータ':'Stored data','データのアクセス状況':'Data access','データのエクスポート':'Export data','アプリデータの削除':'Delete app data','ランニング計測':'Run tracking','位置情報と時刻を距離計測に利用します。計測開始時に位置情報の許可を求めます。':'Location and time are used to measure distance. Location permission is requested when you start.','必須・サービス利用中':'Required while tracking','健康・運動分析':'Activity insights','過去の走行データを使って、月次インサイトや運動傾向を生成します。':'Use your run history to show monthly activity insights.','有効期限：設定なし':'No expiry set','研究・統計利用':'Research and statistics','研究へのデータ提供は準備中です。現在は送信しません。':'Research sharing is not available. No data is sent.','現在、共有先はありません':'No sharing partners','マーケティング通知':'Marketing notifications','通知配信は準備中です。現在は送信しません。':'Notifications are not available. No messages are sent.','現在は未配信':'Not enabled','表示':'Display','言語 / Language':'Language','単位':'Units','通知':'Notifications','チャレンジ通知':'Challenge notifications','アカウント':'Account','ログアウト':'Sign out','ホーム':'Home','ラン':'Run','マイページ':'My page','走行ルート':'Run route',
'端末保存モード · このブラウザに保存します':'Device storage · saved in this browser','クラウド保存 · PDLは未連携':'Cloud storage · PDL not connected','開催情報を確認':'View campaign details','認定ランを集計':'Verified runs only','未参加':'Not joined','認定された距離を集計':'Verified distance only','今月の距離':'Distance this month','今月の走行日数':'Running days this month','運動分析はオフです。同意管理から変更できます。':'Activity insights are off. Enable them in Consent.','あなたのデータは、あなたが管理する。\nPDL連携は準備中':'Your data. Your control.\nPDL integration is coming soon.',
'GPS軌跡（背景地図なし）':'GPS route (no basemap)','GPSを取得すると軌跡が表示されます':'Your route appears when GPS is available','待機中':'Waiting','位置精度 —':'Accuracy —','STARTで位置情報の取得を開始します。':'Press START to request your location.','GPSを再取得':'Retry GPS','取得中':'Acquiring location','取得済み':'Location acquired','精度を改善中':'Improving accuracy','許可が必要':'Permission required','再取得待ち':'Waiting to retry','位置情報の利用を許可してください。屋外では精度が改善します。':'Allow location access. Accuracy improves outdoors.','現在地は概算です。精度50m以内になると距離に加算します。':'Approximate location. Distance is counted when accuracy is within 50 m.','一時停止中です。再開を押すと距離計測を続けます。':'Paused. Press Resume to continue measuring distance.','GPSを取得しました。移動すると軌跡と距離を更新します。':'GPS ready. Your route and distance update as you move.','端末とブラウザの位置情報を許可し、GPSを再取得してください。アプリ内ブラウザの場合はSafariまたはChromeで開いてください。':'Allow location access in your device and browser settings, then retry GPS. If using an in-app browser, open this page in Safari or Chrome.','GPS取得がタイムアウトしました。屋外でGPSを再取得してください。':'GPS timed out. Move outdoors and retry.','現在地を取得できません。端末の位置情報をオンにして再取得してください。':'Location unavailable. Enable device location services and retry.','GPS計測にはHTTPSと位置情報対応ブラウザが必要です。':'GPS requires HTTPS and a browser with location support.','位置精度を確認中':'Checking location accuracy','速すぎる移動を除外しました':'Excluded movement above the running speed limit','STARTで計測開始':'Press START to begin','一時停止中':'Paused','ランニング中…':'Running…',
'プロフィール画像を変更':'Change profile photo','プロフィール画像':'Profile photo','JPEG・PNG・WebP、10MBまで。中央を正方形に切り抜きます。':'JPEG, PNG or WebP, up to 10 MB. Photos are cropped to a centered square.','画像をリセット':'Reset photo','ニックネーム':'Nickname','国・地域':'Country / region','保存':'Save','プロフィールを保存しました。':'Profile saved.','JPEG・PNG・WebPの画像を選択してください。':'Select a JPEG, PNG or WebP image.','画像は10MB以下にしてください。':'Choose an image smaller than 10 MB.','画像を読み込めませんでした。別の画像を選択してください。':'Could not read this image. Choose another one.','閉じる':'Close',
'メールでログイン':'Sign in with email','メールアドレス':'Email address','パスワード（8文字以上）':'Password (at least 8 characters)','ログイン':'Sign in','新規登録':'Sign up','確認メールを送信しました。メール内のリンクを開いてからログインしてください。':'Confirmation email sent. Open the link in the email, then sign in.','この端末に保存して使う':'Save on this device','走行記録と位置の軌跡を、このブラウザに保存します。ブラウザのデータ削除で記録も消えます。PDLやクラウドには送信されません。':'Your runs and routes are stored in this browser. Clearing browser data removes them. Nothing is sent to PDL or the cloud.','端末保存で始める':'Start with device storage','読み込み中…':'Loading…','ランキングはクラウドログイン後に利用できます。':'Sign in to the cloud to use rankings.','この条件の認定記録はまだありません。':'No verified runs match these filters.','チームに参加して、仲間と走ろう。':'Join a team and run together.','チーム名':'Team name','参加・新規作成':'Join / Create','まだ参加していません。':'You have not joined a team yet.','チームに参加すると累計距離が表示されます。':'Join a team to see its total distance.','チームに参加しました。':'Joined the team.','参加後の認定済み記録をチームに加算します。':'Verified runs completed after joining count toward your team.','チームに招待する':'Invite to team','今月の認定距離 km':'Verified distance this month (km)','チームで日本を縦断しよう':'Run across Japan as a team','現在開催中のチャレンジはありません。画像は企画イメージです。':'No challenges are currently open. Images show the campaign concept.','開催情報の公開をお待ちください。':'Campaign details will be announced here.','未定':'To be announced','このチャレンジに参加':'Join this challenge','参加登録しました。':'You have joined the challenge.','過去のチャレンジはありません。':'No past challenges.',
'ランニングを終了しますか？':'Finish this run?','計測を終了し、走行履歴に保存します。':'Stop tracking and save to your run history.','終了して保存':'Finish and save','続ける':'Continue','走行記録を保存しました。':'Run saved.','保存中…':'Saving…','保存に失敗・再保存':'Save failed · retry','タップして再保存してください':'Tap to retry saving','この端末に保存しました。ランキング対象外です。':'Saved on this device. Not included in rankings.','保存しました。サーバーでの認定前です。':'Saved. Awaiting server verification.','推定 kcal（体重60kg）':'Estimated kcal (60 kg body weight)','1 kmごとの実測スプリットがここに表示されます。':'Measured splits appear here after each kilometer.','未認定':'Unverified','認定済み':'Verified','走行履歴':'Run history','まだ走行記録がありません。ホームのSTART RUNから始めましょう。':'No runs yet. Select START RUN on Home to begin.','ランキング公開':'Public rankings','ニックネーム、国・地域、認定距離を他のログイン利用者へ公開します。位置の軌跡は公開しません。':'Share your nickname, country and verified distance with signed-in users. Your route stays private.','ランキング公開設定を保存しました。':'Ranking visibility saved.','同意設定を保存しました。':'Consent settings saved.','全走行記録をエクスポートしました。':'Exported all runs.','距離とペースの表示単位を変更しました。月間目標・ランキングはkm基準です。':'Distance and pace units updated. Monthly goals and rankings use kilometers.',
'走行結果を共有':'Share your run','距離・時間・ペースだけを画像にします。位置情報やルートは含めません。':'Create an image with distance, time and pace only. Location and route are excluded.','共有画像を保存':'Save share image','先に走行記録を選択してください。':'Select a run first.','チームを退出':'Leave team','チームを退出しました。':'You left the team.','参加中のチームから退出できます。記録そのものは残ります。':'You can leave your current team. Your runs will be kept.','招待リンクをコピーしました。':'Invite link copied.','招待リンク':'Invite link','アプリデータを削除':'Delete app data','走行履歴、プロフィール、同意設定、チーム参加、チャレンジ参加を削除します。元に戻せません。ログインアカウント自体は残ります。':'Delete your runs, profile, consent settings, team membership and challenge entries. This cannot be undone. Your login account will remain.','すべてのアプリデータを削除':'Delete all app data','アプリデータを削除しました。':'App data deleted.','計測を終了し、未保存の記録を保存してから削除してください。':'Finish tracking and save your run before deleting data.','計測を終了し、記録を保存してからログアウトしてください。':'Finish tracking and save your run before signing out.','未保存の走行記録を再保存してください。':'Retry saving your unsaved run.','前の記録を保存してから開始してください。':'Save your previous run before starting another.','保存できませんでした。「再保存」を押してください。この画面は閉じないでください。':'Could not save. Tap Retry save and keep this page open.','処理に失敗しました。もう一度お試しください。':'Something went wrong. Please try again.',
};
Object.assign(en,{"Jasmy PDL連携は準備中": "Jasmy PDL integration is coming soon", "GPS計測について": "About GPS tracking", "GPS軌跡": "GPS route", "ランキングの集計": "How rankings work", "チャレンジへの参加": "Joining challenges", "データの取り扱い（開発版）": "Data handling (development version)", "開発版の利用について": "About this development version", "PDLの認証先とAPI接続はまだ設定されていません。PDLへデータは送信されません。Googleログイン、または端末保存をご利用ください。": "PDL authentication and API connections are not configured. No data is sent to PDL. Use Google sign-in or device storage.", "PDLへの接続は準備中です。端末保存モードではこのブラウザ内に保存します。クラウドモードではログインした本人の走行記録を保存します。": "PDL is not connected yet. Device mode saves records in this browser. Cloud mode saves the signed-in user’s running records.", "PDLのアクセス監査ログは未接続です。この画面では第三者によるアクセス履歴の確認はまだできません。": "PDL access audit logs are not connected. Third-party access history is not available on this screen yet.", "高精度GPSを利用します。画面を開いたまま計測してください。画面ロックやバックグラウンドでの継続計測は保証されません。位置精度が50mを超える点や30秒を超える取得間隔は距離に加算しません。": "High-accuracy GPS is used. Keep this page open while tracking. Tracking with the screen locked or in the background is not guaranteed. Points with accuracy worse than 50 m and gaps longer than 30 seconds are excluded from distance.", "実際に取得した位置の軌跡を表示しています。背景の地図サービスには接続していません。共有画像には軌跡と位置情報を含めません。": "This shows your recorded GPS route. A background map service is not connected. Shared images exclude routes and location.", "認定済みで、ランキング公開に同意した人の距離だけを集計します。期間はUTC基準です。端末保存の記録や未認定の記録は対象外です。": "Only verified distances from users who opt into public rankings are counted. Periods use UTC. Device-only and unverified runs are excluded.", "開催中の企画に参加登録し、条件を満たす認定ランがある日に1口を付与します。賞品、開催期間、抽選は運営による設定が必要です。": "Join an open challenge to earn one entry per day with a qualifying verified run. The operator must configure prizes, dates and draws.", "GPS取得は「位置情報を許可する」を押した後に行います。端末保存モードの記録はこのブラウザ内に保存され、クラウドやPDLへ送られません。クラウドログイン時はSupabaseに記録とプロフィールを保存します。位置の詳細はランキングに公開しません。エクスポートと削除はマイページから行えます。正式公開前に運営者・問い合わせ先・保存期間を含むポリシーの確定が必要です。": "GPS is requested when you tap Allow location access. Device mode keeps runs in this browser and sends nothing to the cloud or PDL. In cloud mode, Supabase stores your runs and profile. Detailed locations are not published in rankings. You can export and delete data from My page. A final policy covering the operator, contact details and retention periods is required before launch.", "このアプリは開発版です。GPSによる距離には誤差があります。安全な場所で利用し、画面操作は立ち止まって行ってください。PDL連携、正式な走行認定、賞品抽選はまだ運用されていません。正式な利用規約は公開前に確定します。": "This is a development version. GPS distance may be inaccurate. Use it in a safe place and stop before interacting with the screen. PDL integration, official run verification and prize draws are not operating yet. Final terms will be provided before launch."});
Object.assign(en,{"位置情報を許可する": "Allow location access", "現在地を確認してから、ランニングを始めましょう。": "Check your current location before starting your run.", "下の「位置情報を許可する」をタップ": "Tap Allow location access below.", "Safariの確認画面で「許可」を選択": "Select Allow in the Safari prompt.", "現在地が表示されたら、ランニングを開始": "Start your run after your location appears.", "位置情報はまだ取得していません。": "Your location has not been acquired yet.", "現在地の確認": "Current location preview", "この位置でランニング開始": "Start running from here", "許可画面が出ない・取得できない場合": "No prompt or location unavailable?", "iPhoneの「設定」→「プライバシーとセキュリティ」→「位置情報サービス」をオンにします。": "On iPhone, open Settings → Privacy & Security → Location Services and turn it on.", "「SafariのWebサイト」で位置情報の利用を許可し、「正確な位置情報」をオンにします。": "Allow location access for Safari Websites and turn on Precise Location.", "Safariのページメニュー→「Webサイトの設定」→「位置情報」を「確認」または「許可」にします。": "In Safari’s page menu, open Website Settings → Location and choose Ask or Allow.", "このページへ戻り、もう一度「位置情報を許可する」をタップします。": "Return to this page and tap Allow location access again.", "iOSのバージョンによって表示名が異なる場合があります。設定アプリをこのページから自動で開くことはできません。": "Labels may vary by iOS version. This page cannot automatically open the Settings app.", "Appleの位置情報設定ガイド": "Apple location settings guide", "位置情報なしで画面を見る": "View running screen without location", "軌跡の表示例を見る": "Preview a sample route", "表示例です。実際の現在地・走行記録ではありません。保存されません。": "Sample only. This is not your location or a recorded run, and will not be saved.", "軌跡の表示例": "Sample route", "計測中はSafariを開いたままにしてください。画面ロック中の継続計測は保証されません。": "Keep Safari open while tracking. Tracking with the screen locked is not guaranteed.", "現在地を取得しました。移動すると軌跡が表示されます。": "Location acquired. Your route appears as you move.", "Safariの確認画面で「許可」を選択してください。現在地を取得しています…": "Select Allow in Safari. Acquiring your location…", "位置情報を再確認する": "Check location again", "現在地を取得しました。ランニングを開始できます。": "Location acquired. You can start running.", "現在地は概算です。「正確な位置情報」をオンにすると軌跡と距離を計測しやすくなります。": "Your location is approximate. Enable Precise Location for better route and distance tracking.", "位置情報が許可されていません。下の設定手順を確認してください。": "Location access is denied. Follow the settings instructions below.", "取得に時間がかかっています。屋外で、もう一度お試しください。": "Location is taking longer than expected. Move outdoors and try again.", "SafariでHTTPSのアプリURLを直接開いてください。": "Open the HTTPS app URL directly in Safari.", "現在地を取得できません。位置情報サービスの設定を確認してください。": "Location unavailable. Check your Location Services settings.", "軌跡の表示例・保存されません": "Sample route · not saved"});
Object.assign(en,{"毎月開催・ご当地グルメ": "Monthly regional gourmet prizes", "北海道のカニ・いくら・ホタテのイメージ": "Illustration of Hokkaido crab, salmon roe and scallops", "賞品イメージ": "Prize illustration", "毎月、走ってご当地グルメに応募": "Run for regional gourmet prizes every month", "毎月開催するチャレンジで、全国のご当地グルメが当たります。当選者はこのページにニックネームで掲示します。": "Join monthly challenges for a chance to win regional gourmet prizes from across Japan. Winners will be listed on this page by nickname.", "賞品の受取には、PDLによるマイナンバーカード認証が必要です。": "Receiving a prize requires My Number Card identity verification through PDL.", "賞品受取には、PDLによるマイナンバーカード認証が必要です。": "Receiving a prize requires My Number Card identity verification through PDL.", "当選者発表": "Winner announcements", "開催月を選択": "Select challenge month", "発表待ち": "Awaiting announcement", "当選者の発表をお待ちください。": "Winners have not been announced yet.", "当選された方へ": "For winners", "受取手続きについて": "How to receive your prize", "賞品の受取について": "Receiving your prize", "当選者はニックネームで発表します。賞品の受取には、PDLによるマイナンバーカード認証が必要です。現在、認証サービスとの接続を準備しています。受取手続きの開始後に、このページでご案内します。": "Winners are announced by nickname. Prize receipt requires My Number Card identity verification through PDL. The verification service is being connected. Instructions will appear here when prize claims open.", "当選者を読み込めませんでした。": "Could not load winners.", "再読み込み": "Retry"});
Object.assign(en,{"Googleでログイン": "Sign in with Google", "クラウド接続の準備中": "Cloud connection not configured", "Googleログインはまだ設定されていません。「この端末だけに保存して使う」から計測を始められます。": "Google sign-in is not configured yet. Start tracking with “Use device storage.”", "Apple Watch連携（Duffy）": "Apple Watch sync (Duffy)", "自作アプリ「Duffy」から歩数・走行距離を同期できます。クラウドへログインすると設定できます。ランキングや認定距離、チャレンジの集計には使いません。": "Sync steps and distance from your own “Duffy” app. Sign in to the cloud to set this up. It is not used for rankings, verified distance or challenge entries.", "自作アプリ「Duffy」から歩数・走行距離を同期できます。ランキングや認定距離、チャレンジの集計には使いません。": "Sync steps and distance from your own “Duffy” app. It is not used for rankings, verified distance or challenge entries.", "状態：連携中": "Status: Connected", "状態：未連携": "Status: Not connected", "連携コードを再発行する": "Reissue sync code", "連携コードを発行する": "Issue sync code", "連携を解除": "Disconnect", "Duffy側からこの内容でPOSTするよう設定してください。コードは発行時に一度だけ表示されます。": "Configure Duffy to POST this. The code is shown only once, when issued.", "連携コードを発行しました": "Sync code issued", "このコードは今だけ表示されます。Duffyの設定に貼り付けてください。再表示はできません。": "This code is shown only now. Paste it into Duffy’s settings — it cannot be shown again.", "コピーする": "Copy", "コピーしました。": "Copied.", "連携コード": "Sync code", "連携を解除しました。": "Disconnected.", "歩・": "steps ·", "km（Apple Watch・未認定）": "km (Apple Watch · unverified)", "広告の内容は表示サンプルです。": "This ad shows sample content.", "スポンサー広告": "Sponsor ad"});
let language='ja';try{language=localStorage.getItem('jasmy-language')==='en'?'en':'ja'}catch{}
export const locale=()=>language==='en'?'en-US':'ja-JP';
export function translate(value){
 if(language!=='en')return value;
 if(en[value])return en[value];
 return value.replace(/^位置精度 ±(\d+)m$/,'Accuracy ±$1 m').replace(/^総距離 (km|mi)$/,'Total distance $1').replace(/^平均ペース \/(km|mi)$/,'Avg. pace /$1').replace(/^ペース \/(km|mi)$/,'Pace /$1').replace(/^平均速度 (km|mi)\/h$/,'Avg. speed $1/h').replace(/^(.*?)さん ☀️$/,'$1 ☀️').replace(/^(.*?)・未認定$/,'$1 · Unverified').replace(/^(.*?) 認定済み$/,'$1 Verified').replace(/^累計認定距離 /,'Total verified distance ').replace(/^認定距離 (.*?) km以上の日が対象です。1日1口。$/,'Days with at least $1 km verified qualify. One entry per day.');
}
const originals=new WeakMap();let observer;
function apply(root){
 const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);let node;
 while(node=walker.nextNode()){
  if(node.parentElement?.closest('script,style,[translate="no"],.language-choice option,input,textarea'))continue;
  const old=originals.get(node),current=node.nodeValue;
  const source=old&&old.rendered===current?old.source:current;
  const trimmed=source.trim(),rendered=source.replace(trimmed,translate(trimmed));
  originals.set(node,{source,rendered});if(current!==rendered)node.nodeValue=rendered;
 }
 // Accessible names use the same catalog and restore their Japanese originals.
 for(const el of root.querySelectorAll?.('[aria-label],[placeholder],img[alt]')||[]){
  for(const attr of ['aria-label','placeholder','alt'])if(el.hasAttribute(attr)){
   const key='i18n'+attr.replace('-',''),old=el.dataset[key];
   if(!old)el.dataset[key]=el.getAttribute(attr);
   el.setAttribute(attr,translate(old||el.getAttribute(attr)));
  }
 }
}
export function initLanguage(onChange){
 const selects=[...document.querySelectorAll('.language-choice')];selects.forEach(select=>select.value=language);
 function refresh(){observer?.disconnect();document.documentElement.lang=language;apply(document.body);observer?.observe(document.body,{subtree:true,childList:true,characterData:true});}
 observer=new MutationObserver(refresh);refresh();
 selects.forEach(select=>select.addEventListener('change',()=>{language=select.value==='en'?'en':'ja';selects.forEach(other=>other.value=language);try{localStorage.setItem('jasmy-language',language)}catch{}onChange();refresh();}));
}

Object.assign(en,{"メールアドレスでログイン":"Sign in with email","メールアドレス":"Email address","パスワードは不要です。メールに届く認証リンクからログインできます。初めての方も同じ手順で登録できます。":"No password needed. Open the sign-in link sent to your email. New users can register the same way.","メールアドレスでログインして、":"Sign in with your email","あなたの記録を管理しましょう。":"to manage your activity records."});

Object.assign(en,{'新規登録':'Create an account'});

Object.assign(en,{'PDLでログイン':'Sign in to PDL','パスワード':'Password','ログイン':'Sign in','確認メールを送信して登録':'Send confirmation email','パスワードを設定・変更':'Set or change password'});
